services:
  mcp:
    build:
      context: .
      args:
        - APP_PORT="${APP_PORT:-8000}"
    environment:
      APP_PORT: "${APP_PORT:-8000}"
      LOG_LEVEL: "DEBUG"
    ports:
    - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    networks: [net]
networks:
  net:
    driver: bridge
# volumes:
#   database:
#     driver: local
